---
apiVersion: v1
kind: Pod # TODO make these deployments later
metadata:
  name: test-pod-no-vhu 
  annotations:
    networks: '[
        { "name": "br-net-1" },
    ]'
spec:
  containers:
  - name: test-pod-no-vhu
    image: "ubuntu:14.04"
    stdin: true
    tty: true
